### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by taytus** [SzymonDukla/HolidayAPI-Wrapper#1]
Hello Szymon, just wondering if you are going to share the source code.
Thank you!

**Comment by SzymonDukla** [comment]
Hello, yes, I'm going to share the wrapper source code but as per Holiday API website, I have tonnes of other projects along with professional life that takes whole loads of time. However, you can have my word I'll put the code here by the end of December. Cheers!

**Comment by taytus** [comment]
That's awesome news!
Thank you so much 👊🏼

**Comment by SzymonDukla** [comment]
@taytus happy to say the code is now available here and via Composer `composer require szymondukla/holiday-api-wrapper`
