### ISSUE TITLE
SQL error for `api_usage` table.

### ISSUE THREAD

**Issue by psalkowski** [SzymonDukla/HolidayAPI-Wrapper#2]
**Describe the bug**
When you want to make a call with only mandatory fields like `year` and `country`, Slim throws an error 
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'month' cannot be null (SQL: insert into `api_usage` (`id`, `endpoint`, `country`, `year`, `month`, `day`, `previous`, `upcoming`, `pretty`, `ip_address`, `status`, `timestamp`) values (, /v1/holidays, PL, 2019, , , 0, 0, 0, XXXX, 200, 2019-03-18 14:02:57))
```

It looks like your's `api_isage` table doesn't follow mandatory parameters: https://github.com/SzymonDukla/HolidayAPI-Wrapper#parameters

**To Reproduce**
Visit https://holidayapi.pl/v1/holidays?year=2019&country=PL and you will see an error.

**Comment by SzymonDukla** [comment]
Hello @namerci 

thank you for reporting this serious bug. Please be assured that this issue has been taken care of and should not be present anymore. Please feel free to re-open this issue if the error will still occur.

Regards,
SD

**Comment by psalkowski** [comment]
You are so fast! :) Thanks a lot.

PS. This service is awesome!
