### ISSUE TITLE
Store/bank holidays

### ISSUE THREAD

**Issue by clarkk** [SzymonDukla/HolidayAPI-Wrapper#5]
It would also be nice to see on which dates the stores are closed..

And the same with banks.. Stores and banks are not closed on the same dates

**Comment by SzymonDukla** [comment]
@clarkk thank you for this suggestion. I am currently working (finalizing actually) on a new version of Holiday API where that kind of information will be available, along with some extra features.

Please check out holidayapi.pl from time to time in the next couple of weeks to stay up-to-date with newest features and countries as well as changes in the API.

Regards,
Szymon

**Comment by clarkk** [comment]
sounds good

especially bank holidays would be interesting..

about the dates when stores are closed can of cource vary from each store/shop

**Comment by SzymonDukla** [comment]
hopefully will see you using the new version, should release around end of the month :) 

of course I won't be able to provide 100% accurate information including each store vendor and regional differences in the amount of countries I'm planning (150+), but I am going to provide a special "data supporter" program which will hopefully encourage residents of those countries to help make this API the most accurate as possible
